package evidencebundle

import (
	"crypto/sha256"
	"encoding/hex"
	"encoding/json"
	"fmt"
	"io"
	"os"
	"path/filepath"
	"sort"
)

const manifestSchemaVersion = "scrap.evidence.bundle/v1"

type bundleManifest struct {
	SchemaVersion        string                  `json:"schema_version"`
	BundleName           string                  `json:"bundle_name"`
	Scenario             string                  `json:"scenario"`
	GeneratedAt          string                  `json:"generated_at"`
	PrivacyStatus        string                  `json:"privacy_status"`
	PrivacyFindingsCount int                     `json:"privacy_findings_count"`
	Provenance           manifestProvenance      `json:"provenance"`
	Environment          manifestEnvironment     `json:"environment"`
	Commands             []manifestCommand       `json:"commands"`
	Artifacts            []manifestArtifact      `json:"artifacts"`
	Evidence             []manifestEvidenceState `json:"evidence"`
}

type manifestProvenance struct {
	GitSHA      string `json:"git_sha"`
	GitSHAShort string `json:"git_sha_short"`
	GitDirty    bool   `json:"git_dirty"`
	Image       string `json:"image"`
	Replicas    int    `json:"replicas"`
}

type manifestEnvironment struct {
	Namespace   string `json:"namespace"`
	KubeContext string `json:"kube_context,omitempty"`
	Cluster     string `json:"cluster"`
}

type manifestCommand struct {
	Name        string `json:"name"`
	Command     string `json:"command"`
	Artifact    string `json:"artifact"`
	Passive     bool   `json:"passive"`
	Description string `json:"description"`
}

type manifestArtifact struct {
	Path        string `json:"path"`
	SizeBytes   int64  `json:"size_bytes"`
	SHA256      string `json:"sha256"`
	ContentType string `json:"content_type"`
}

type manifestEvidenceState struct {
	Area       string `json:"area"`
	Status     string `json:"status"`
	Artifact   string `json:"artifact,omitempty"`
	Reason     string `json:"reason"`
	Owner      string `json:"owner"`
	Mitigation string `json:"mitigation,omitempty"`
}

func writeManifest(cfg Config, state generationState, gate Gate, privacy privacyScanReport) error {
	run, err := readRunConfig(state.paths.root)
	if err != nil {
		return err
	}
	artifacts, err := collectManifestArtifacts(state.paths.root)
	if err != nil {
		return err
	}
	manifest := bundleManifest{
		SchemaVersion:        manifestSchemaVersion,
		BundleName:           filepath.Base(state.paths.root),
		Scenario:             cfg.Scenario,
		GeneratedAt:          run.Timestamp,
		PrivacyStatus:        privacy.Status,
		PrivacyFindingsCount: privacy.FindingsCount,
		Provenance: manifestProvenance{
			GitSHA:      run.GitSHA,
			GitSHAShort: run.GitSHAShort,
			GitDirty:    run.GitDirty,
			Image:       run.Image,
			Replicas:    run.Replicas,
		},
		Environment: manifestEnvironment{
			Namespace:   cfg.Namespace,
			KubeContext: cfg.KubeContext,
			Cluster:     run.Cluster,
		},
		Commands:  manifestCommands(cfg),
		Artifacts: artifacts,
		Evidence:  manifestEvidence(cfg, state, gate, privacy),
	}
	return writeJSONFile(filepath.Join(state.paths.root, "manifest.json"), manifest)
}

func readRunConfig(root string) (runConfig, error) {
	data, err := os.ReadFile(filepath.Join(root, "config.json")) //nolint:gosec // config path is inside the generated bundle.
	if err != nil {
		return runConfig{}, fmt.Errorf("read run config for manifest: %w", err)
	}
	var run runConfig
	if err := json.Unmarshal(data, &run); err != nil {
		return runConfig{}, fmt.Errorf("parse run config for manifest: %w", err)
	}
	return run, nil
}

func collectManifestArtifacts(root string) ([]manifestArtifact, error) {
	var artifacts []manifestArtifact
	err := filepath.WalkDir(root, func(path string, entry os.DirEntry, err error) error {
		if err != nil {
			return err
		}
		if entry.IsDir() {
			return nil
		}
		rel, err := filepath.Rel(root, path)
		if err != nil {
			return fmt.Errorf("rel manifest path %s: %w", path, err)
		}
		rel = filepath.ToSlash(rel)
		if rel == "manifest.json" {
			return nil
		}
		artifact, err := manifestArtifactForPath(path, rel)
		if err != nil {
			return err
		}
		artifacts = append(artifacts, artifact)
		return nil
	})
	if err != nil {
		return nil, fmt.Errorf("walk bundle artifacts for manifest: %w", err)
	}
	sort.Slice(artifacts, func(i, j int) bool {
		return artifacts[i].Path < artifacts[j].Path
	})
	return artifacts, nil
}

func manifestArtifactForPath(path, rel string) (manifestArtifact, error) {
	file, err := os.Open(path) //nolint:gosec // path is generated by walking the bundle directory.
	if err != nil {
		return manifestArtifact{}, fmt.Errorf("open artifact %s: %w", rel, err)
	}
	defer func() { _ = file.Close() }()
	hash := sha256.New()
	size, err := io.Copy(hash, file)
	if err != nil {
		return manifestArtifact{}, fmt.Errorf("hash artifact %s: %w", rel, err)
	}
	return manifestArtifact{
		Path:        rel,
		SizeBytes:   size,
		SHA256:      hex.EncodeToString(hash.Sum(nil)),
		ContentType: manifestContentType(rel),
	}, nil
}

func manifestContentType(rel string) string {
	if filepath.Ext(rel) == ".json" {
		return "application/json"
	}
	return "text/plain"
}

func manifestCommands(cfg Config) []manifestCommand {
	return []manifestCommand{
		{Name: "stress", Command: "go run ./test/stress", Artifact: "stress-results.json", Passive: true, Description: "current-run workload evidence"},
		{Name: "admin_health_probe", Command: "GET /healthz with X-Scrap-Evidence-Marker", Artifact: "logs/evidence-probe-health.json", Passive: true, Description: "status, security mode, Shard, scanner, and quarantine health snapshot"},
		{Name: "metrics", Command: "Prometheus instant queries via configured Mimir proxy", Artifact: "metrics/", Passive: true, Description: "RPC, upload, eviction, scanner, security, Raft, and runtime metric snapshots"},
		{Name: "traces", Command: "Tempo search for service.name=scrapd", Artifact: "traces/scrapd.json", Passive: true, Description: "redacted trace-count evidence"},
		{Name: "logs", Command: "Loki query for generated evidence marker", Artifact: "logs/scrapd.json", Passive: true, Description: "current-run log marker evidence"},
		{Name: "profiles", Command: "Pyroscope render queries", Artifact: "profiles/", Passive: true, Description: "CPU and heap profile evidence"},
		{Name: "security_report", Command: "copy configured security evidence report", Artifact: "security/e2e-report.json", Passive: true, Description: "production-security rehearsal summary"},
		{Name: "eviction_status", Command: "GET /admin/eviction/plans/<redacted-plan-id>", Artifact: "eviction/", Passive: true, Description: evictionCommandDescription(cfg)},
		{Name: "privacy_scan", Command: "scan generated bundle artifacts for forbidden evidence shapes", Artifact: "privacy-scan.json", Passive: true, Description: "release-sensitive leak scan"},
	}
}

func evictionCommandDescription(cfg Config) string {
	if cfg.EvictionPlanID == "" {
		return "eviction plan not configured; manifest records concern"
	}
	return "eviction campaign status and validation evidence"
}

func manifestEvidence(cfg Config, state generationState, gate Gate, privacy privacyScanReport) []manifestEvidenceState {
	root := state.paths.root
	return []manifestEvidenceState{
		fileEvidence(root, "status", "logs/evidence-probe-health.json", "admin health/status snapshot captured"),
		fileEvidence(root, "leaders", "metrics/raft_is_leader.json", "Raft leader metric captured"),
		concernEvidence("peers", "Story 6.5 / Tier 2 gate", "passive bundle does not invoke scrapctl peers yet", "Link Tier 2 peer evidence or add safe passive peer collection."),
		fileEvidence(root, "upload_pressure", "metrics/upload_pressure.json", "upload pressure metric captured"),
		concernEvidence("faults", "release owner", "fault commands are intentionally non-passive and not run by release bundle", "Link controlled non-production fault drill evidence."),
		evictionEvidence(cfg),
		fileEvidence(root, "shard_health", "metrics/raft_is_leader.json", "Shard leadership metric captured"),
		fileEvidence(root, "scanner_quarantine", "metrics/avscan_lag_blocks.json", "scanner lag metric captured; quarantine status is included in admin health when present"),
		gateEvidence("openbao_readiness", "security/e2e-report.json", "release owner / Epic 4", gate, "security_mode_recorded", "security and OpenBao readiness evidence recorded"),
		gateEvidence("telemetry", "metrics/rpc_requests.json", "release owner / Story 6.5", gate, "metrics_captured", "required current-run metrics captured"),
		gateEvidence("traces", "traces/scrapd.json", "release owner / Story 6.5", gate, "traces_captured", "redacted trace evidence captured"),
		gateEvidence("logs", "logs/scrapd.json", "release owner / Story 6.5", gate, "logs_captured", "current-run log marker captured"),
		gateEvidence("profiles", "profiles/", "release owner / Story 6.5", gate, "cpu_profile_captured", "profile evidence captured"),
		gateEvidence("security", "security/e2e-report.json", "release owner / Epic 4", gate, "authorization_denials_recorded", "authorization denial proof recorded"),
		privacyEvidence(state, privacy),
	}
}

func fileEvidence(root, area, artifact, passReason string) manifestEvidenceState {
	if _, err := os.Stat(filepath.Join(root, filepath.FromSlash(artifact))); err == nil {
		return manifestEvidenceState{Area: area, Status: "PASS", Artifact: artifact, Reason: passReason, Owner: "release owner"}
	}
	return manifestEvidenceState{Area: area, Status: "FAIL", Artifact: artifact, Reason: "required artifact missing", Owner: "release owner", Mitigation: "rerun bundle after fixing artifact generation"}
}

func concernEvidence(area, owner, reason, mitigation string) manifestEvidenceState {
	return manifestEvidenceState{Area: area, Status: "CONCERNS", Reason: reason, Owner: owner, Mitigation: mitigation}
}

func evictionEvidence(cfg Config) manifestEvidenceState {
	if cfg.EvictionPlanID == "" {
		return concernEvidence("eviction_restore", "release owner / Epic 3", "eviction plan id not configured for this bundle", "Run bundle with --eviction-plan-id when release proof requires an eviction campaign.")
	}
	return manifestEvidenceState{Area: "eviction_restore", Status: "PASS", Artifact: "eviction/status.json", Reason: "eviction campaign evidence captured", Owner: "release owner / Epic 3"}
}

func gateEvidence(area, artifact, owner string, gate Gate, checkName, passReason string) manifestEvidenceState {
	for _, check := range gate.Checks {
		if check.Name != checkName {
			continue
		}
		if check.Pass {
			return manifestEvidenceState{Area: area, Status: "PASS", Artifact: artifact, Reason: passReason, Owner: owner}
		}
		return manifestEvidenceState{Area: area, Status: "FAIL", Artifact: artifact, Reason: check.Reason, Owner: owner, Mitigation: "fix failing gate evidence and rerun bundle"}
	}
	return manifestEvidenceState{Area: area, Status: "FAIL", Artifact: artifact, Reason: "gate check missing: " + checkName, Owner: owner, Mitigation: "restore expected gate check"}
}

func privacyEvidence(state generationState, privacy privacyScanReport) manifestEvidenceState {
	if privacy.Status == privacyStatusPass {
		return manifestEvidenceState{Area: "redaction_proof", Status: "PASS", Artifact: "privacy-scan.json", Reason: state.signals.privacyScanReason, Owner: "release owner"}
	}
	return manifestEvidenceState{Area: "redaction_proof", Status: "FAIL", Artifact: "privacy-scan.json", Reason: state.signals.privacyScanReason, Owner: "release owner", Mitigation: "remove or redact forbidden findings and rerun bundle"}
}
