package evidencebundle

import (
	"bytes"
	"fmt"
	"os"
	"path/filepath"
	"regexp"
)

const (
	privacyScanSchemaVersion = "scrap.evidence.privacy/v1"
	privacyStatusPass        = "PASS"
	privacyStatusFail        = "FAIL"
)

type privacyScanReport struct {
	SchemaVersion    string           `json:"schema_version"`
	Status           string           `json:"status"`
	ArtifactCount    int              `json:"artifact_count"`
	FindingsCount    int              `json:"findings_count"`
	Patterns         []privacyPattern `json:"patterns"`
	Findings         []privacyFinding `json:"findings"`
	SkippedArtifacts []string         `json:"skipped_artifacts"`
}

type privacyPattern struct {
	Name        string `json:"name"`
	Description string `json:"description"`
}

type privacyScanPattern struct {
	privacyPattern
	expr *regexp.Regexp
}

type privacyFinding struct {
	Path    string `json:"path"`
	Pattern string `json:"pattern"`
	Line    int    `json:"line"`
	Reason  string `json:"reason"`
}

func writePrivacyScan(root string) (privacyScanReport, error) {
	report, err := scanBundlePrivacy(root)
	if err != nil {
		return privacyScanReport{}, fmt.Errorf("walk bundle artifacts for privacy scan: %w", err)
	}
	if err := writeJSONFile(filepath.Join(root, "privacy-scan.json"), report); err != nil {
		return privacyScanReport{}, err
	}
	return report, nil
}

func scanBundlePrivacy(root string) (privacyScanReport, error) {
	patterns := bundlePrivacyPatterns()
	report := privacyScanReport{
		SchemaVersion: privacyScanSchemaVersion,
		Status:        privacyStatusPass,
		Patterns:      publicPrivacyPatterns(patterns),
	}
	err := filepath.WalkDir(root, func(path string, entry os.DirEntry, err error) error {
		if err != nil {
			return err
		}
		if entry.IsDir() {
			return nil
		}
		rel, err := filepath.Rel(root, path)
		if err != nil {
			return fmt.Errorf("rel privacy scan path %s: %w", path, err)
		}
		rel = filepath.ToSlash(rel)
		if rel == "manifest.json" || rel == "privacy-scan.json" {
			report.SkippedArtifacts = append(report.SkippedArtifacts, rel)
			return nil
		}
		report.ArtifactCount++
		data, err := os.ReadFile(path) //nolint:gosec // path is generated by walking the bundle directory.
		if err != nil {
			return fmt.Errorf("read privacy scan artifact %s: %w", rel, err)
		}
		report.Findings = append(report.Findings, scanPrivacyArtifact(rel, data, patterns)...)
		return nil
	})
	if err != nil {
		return privacyScanReport{}, fmt.Errorf("walk bundle artifacts for privacy scan: %w", err)
	}
	report.FindingsCount = len(report.Findings)
	if report.FindingsCount > 0 {
		report.Status = privacyStatusFail
	}
	return report, nil
}

func scanPrivacyArtifact(rel string, data []byte, patterns []privacyScanPattern) []privacyFinding {
	var findings []privacyFinding
	for _, pattern := range patterns {
		indexes := pattern.expr.FindAllIndex(data, -1)
		for _, index := range indexes {
			findings = append(findings, privacyFinding{
				Path:    rel,
				Pattern: pattern.Name,
				Line:    1 + bytes.Count(data[:index[0]], []byte("\n")),
				Reason:  pattern.Description,
			})
		}
	}
	return findings
}

func bundlePrivacyPatterns() []privacyScanPattern {
	return []privacyScanPattern{
		newPrivacyPattern("credential_shape", "credential, bearer token, private key, JWT, or cloud access key shape", `(?i)(access[_-]?key|password|token|Bearer[[:space:]]+|AKIA[0-9A-Z]{16}|eyJ[A-Za-z0-9_-]+\.|PRIVATE KEY|BEGIN [A-Z ]*KEY)`),
		newPrivacyPattern("raw_identifier_shape", "raw Document, Transaction, trace, or request identifier field", `(?i)(transaction[_-]?id|transactionId|document[_-]?name|documentName|trace[_-]?id|traceID|request[_-]?id|requestID|x-request-id)[[:space:]":=]+`),
		newPrivacyPattern("backend_key_shape", "raw Backend object key or auth claim marker", `(?i)(backend[_ -]?key|object[_ -]?key|auth claim|Authorization:)`),
		newPrivacyPattern("host_path_shape", "host-absolute path intended for public evidence", `(?i)(^|[[:space:]":])(/(home|Users|var|opt|private|tmp)/|[A-Za-z]:\\|host-absolute)`),
		newPrivacyPattern("payload_or_key_material", "Document payload, data key, wrapped key, or ciphertext marker", `(?i)(document payload|data[_ -]?key|wrapped[_ -]?key|ciphertext|<\?xml|<Invoice)`),
	}
}

func newPrivacyPattern(name, description, expr string) privacyScanPattern {
	return privacyScanPattern{
		privacyPattern: privacyPattern{Name: name, Description: description},
		expr:           regexp.MustCompile(expr),
	}
}

func publicPrivacyPatterns(patterns []privacyScanPattern) []privacyPattern {
	out := make([]privacyPattern, 0, len(patterns))
	for _, pattern := range patterns {
		out = append(out, pattern.privacyPattern)
	}
	return out
}

func privacyGateReason(report privacyScanReport) string {
	if report.Status == privacyStatusPass {
		return fmt.Sprintf("privacy scan passed (%d artifact(s), %d finding(s))", report.ArtifactCount, report.FindingsCount)
	}
	return fmt.Sprintf("privacy scan failed (%d artifact(s), %d finding(s))", report.ArtifactCount, report.FindingsCount)
}
