apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: scrap-local
resources:
  - namespace.yaml
  - ../../base
  - ../../components/local-dependencies
images:
  - name: ghcr.io/petabytecl/scrap/scrapd
    newName: localhost/scrapd
    newTag: local
patches:
  - path: statefulset-admin-ui-patch.yaml
    target:
      kind: StatefulSet
      name: scrapd
labels:
  - includeSelectors: false
    includeTemplates: true
    pairs:
      cl.petabyte.scrap/release-profile: scrap-prod-v1
      cl.petabyte.scrap/environment: local-dev
