kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: scrap-stress
nodes:
  - role: control-plane
    extraPortMappings:
      - containerPort: 30090
        hostPort: 18090
        protocol: TCP
      - containerPort: 30100
        hostPort: 18100
        protocol: TCP
      - containerPort: 30300
        hostPort: 13000
        protocol: TCP
  - role: worker
  - role: worker
  - role: worker
