apiVersion: v1
kind: Service
metadata:
  name: scrap
  namespace: scrap
spec:
  type: ClusterIP
  selector:
    app: scrap
  ports:
    - name: client
      port: 9090
      targetPort: 9090
    - name: metrics
      port: 9100
      targetPort: 9100
