syntax = "proto3";

package scrap.v1;

import "google/protobuf/timestamp.proto";

option go_package = "github.com/petabytecl/scrap/internal/gen/scrap/v1;scrapv1";

message DocumentIdentity {
  string tenant_id = 1;
  string transaction_id = 2;
  string document_name = 3;
}

message TransactionIdentity {
  string tenant_id = 1;
  string transaction_id = 2;
}

message ReadRange {
  uint64 offset = 1;
  optional uint64 length = 2;
}

message TimeRange {
  optional google.protobuf.Timestamp start_time = 1;
  optional google.protobuf.Timestamp end_time = 2;
}
