apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

components:
  - ../../components/localstack
  - ../../components/nodeports

patches:
  - path: statefulset-security-mode-patch.yaml

images:
  - name: ghcr.io/petabytecl/scrap/scrapd
    newName: localhost/scrapd
    newTag: local
