apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: scrapd
  namespace: scrap
spec:
  template:
    spec:
      containers:
        - name: scrapd
          env:
            - name: SCRAP_SECURITY_MODE
              value: development
