apiVersion: v1
kind: Service
metadata:
  name: scrap
  namespace: scrap
spec:
  type: NodePort
  ports:
    - name: client
      port: 9090
      targetPort: 9090
      nodePort: 30090
    - name: metrics
      port: 9100
      targetPort: 9100
      nodePort: 30100
