apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: scrapd
spec:
  replicas: 3
  template:
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                labelSelector:
                  matchLabels:
                    app.kubernetes.io/component: scrapd
                topologyKey: kubernetes.io/hostname
