apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base
  - localstack.yaml

patches:
  - path: service-client-nodeport-patch.yaml
  - path: statefulset-upload-patch.yaml

images:
  - name: ghcr.io/petabytecl/scrap/scrapd
    newName: localhost/scrapd
    newTag: local
