apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: scrap-local
resources:
  - namespace.yaml
  - ../../base
  - localstack.yaml
  - openbao.yaml
images:
  - name: ghcr.io/petabytecl/scrap/scrapd
    newName: localhost/scrapd
    newTag: local
labels:
  - includeSelectors: true
    pairs:
      cl.petabyte.scrap/release-profile: scrap-prod-v1
      cl.petabyte.scrap/environment: local-kind
