apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - collector.yaml
  - mimir.yaml
  - loki.yaml
  - tempo.yaml
  - pyroscope.yaml
  - grafana.yaml
  - grafana-datasources.yaml
