apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: scrapd
  namespace: scrap
spec:
  template:
    spec:
      containers:
        - name: scrapd
          env:
            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              value: http://otel-collector.monitoring.svc:4317
            - name: SCRAP_ENVIRONMENT
              value: stress
            - name: SCRAP_CELL_ID
              value: kind-stress
